sudo: false

language: php

services:
    - docker

php:
    - 7.2
    - 7.3
    - 7.4
    - nightly

matrix:
    allow_failures:
        - php: nightly

install:
    - travis_retry composer install
    - docker-compose -f ./tests/docker-compose.yml up -d
    - php ./tests/wait.php

script:
    - vendor/bin/phpunit --coverage-text

# after_script:
#    - wget https://scrutinizer-ci.com/ocular.phar
#    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
