sudo: false

language: php

services:
    - rabbitmq

php:
    - 7.2
    - 7.3
    - 7.4snapshot
    - nightly

matrix:
    allow_failures:
        - php: 7.4snapshot
        - php: nightly

install:
    - travis_retry composer install

script:
    - php ./tests/wait.php
    - vendor/bin/phpunit --coverage-text

# after_script:
#    - wget https://scrutinizer-ci.com/ocular.phar
#    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
