language: php

services:
    - rabbitmq

php:
    - 7.2

sudo: false

install:
    - travis_retry composer install

script:
    - vendor/bin/phpunit --coverage-text

after_script:
#    - wget https://scrutinizer-ci.com/ocular.phar
#    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover